#!/bin/bash

cd "$(dirname "$0")/../../"
source .vscode/dbg-tools/rpc-env.sh

echo ---- new_invoice ----
payment_preimage="0x$(openssl rand -hex 32)"
CURL_RESPONSE=$(curl -s -X POST \
  -H "Content-Type: application/json" \
  -d '{
    "id": "42",
    "jsonrpc": "2.0",
    "method": "new_invoice",
    "params": [{
      "amount": "0x2540be400",
      "currency": "Fibt",
      "description": "test invoice generated by node3",
      "expiry": "0xe10",
      "payment_preimage": "'$payment_preimage'",
      "hash_algorithm": "sha256"
    }]
  }' http://localhost:8247)
EXIT_CODE=$?
echo "$CURL_RESPONSE"
echo ""
echo ---- ExitCode: $EXIT_CODE ----

if [ $EXIT_CODE -ne 0 ]; then
  exit $EXIT_CODE
fi

INVOICE_ADDRESS=$(node -e '
const input = process.argv[1] || "";
try {
  const parsed = JSON.parse(input);
  const invoiceAddress = parsed?.result?.invoice_address;
  if (!invoiceAddress || typeof invoiceAddress !== "string") {
    process.exit(1);
  }
  process.stdout.write(invoiceAddress);
} catch {
  process.exit(1);
}
' "$CURL_RESPONSE")
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  echo "Failed to parse invoice_address from new_invoice response"
  exit $EXIT_CODE
fi


echo ---- send_payment ----
PAYLOAD=$(cat <<EOF
{
  "id": "42",
  "jsonrpc": "2.0",
  "method": "send_payment",
  "params": [{
    "invoice": "$INVOICE_ADDRESS"
  }]
}
EOF
)

curl -s -X POST \
  -H "Content-Type: application/json" \
  -d "$PAYLOAD" http://localhost:8227
EXIT_CODE=$?
echo ""
echo ---- ExitCode: $EXIT_CODE ----
