#!/bin/bash

cd "$(dirname "$0")/../../"
source ./fiber-dbg-scripts/rpc/rpc-env.sh

PAYMENT_PREIMAGE="0x$(openssl rand -hex 32)"

# 1 ckb
AMOUNT=0x5f5e100

CURL_RESPONSE=$(curl -s -X POST \
  -H "Content-Type: application/json" \
  -d '{
    "id": "42",
    "jsonrpc": "2.0",
    "method": "new_invoice",
     "params": [
       {
          "amount": "'$AMOUNT'",
          "currency": "Fibt",
          "description": "test invoice generated by node2",
          "expiry": "0xe10",
          "final_cltv": "0x28",
          "payment_preimage": "'$PAYMENT_PREIMAGE'",
          "hash_algorithm": "sha256"
        }
    ]
  }' http://localhost:$NODE2_PORT)

EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  echo ---- ExitCode: $EXIT_CODE ----
  exit $EXIT_CODE
fi

echo "$CURL_RESPONSE"
